### ISSUE TITLE
Weird filename case handling

### ISSUE THREAD

**Issue by hoba87** [pypa/build#569] opened 2023-01-27 18:03 UTC
I'm working on Windows (11), python 3.9, build 0.10.
I have a package with several files each containing one class. E.g.

- DIR
  - PACKAGENAME
    -` __init__.py`
    -` abc.py`
    -` def.py`

File abc.py look e.g.:
```
class ABC:
  pass
```

In __init__py I import the classes, like:
```
from .abc import ABC
from .def import DEF
```

After building the package with python -m build and installing, I get the error "No module named 'PACKAGENAME.abc'", because the file
in the installed package is renamed to aBC.py

Installing the package with `pip install .` works without problems.

**Comment by henryiii** [comment] 2023-01-27 18:07
Did you verify it can open `PACKAGENAME.aBC`? Windows is case insensitive, so I'd have thought it would be impossible to break like this. What build backend are you using?

**Comment by hoba87** [comment] 2023-01-30 08:42
Yes, I can execute `import PACKAGENAME.aBC`. I'm using setuptools as build backend.

**Comment by henryiii** [comment] 2023-02-03 21:24
`pip install .` skips the SDist and builds the wheel from source. Can you try `pipx run build --wheel` (or `pipx run build --wheel --sdist`) to make build skip the SDist intermediate step too? Do you customize any setuptools steps (especially bdist_wheel)?

**Comment by hoba87** [comment] 2023-02-16 13:45
for both commands I get the same behaviour with the above error. My pyproject.toml does pretty look like standard, probably also the starting is normal?
```
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
```

**Comment by layday** [comment] 2023-02-16 15:51
Did you verify that the casing is incorrect in the wheel file itself prior to installing? A wheel is just a zip file, you can look inside.

What command are you using to install the built wheel?

Would you be able to share the source or a minimal reproducible example?

**Comment by hoba87** [comment] 2023-02-17 14:24
Ok, probably it is a cache problem of the build directory. When I delete the build directory, the problem is gone. I had changed the filename case before, so there was probably still the wrong case in the build cache.

**Comment by layday** [comment] 2023-02-17 14:59
This is https://github.com/pypa/setuptools/issues/1871.  You are probably also using an old version of pip since it now builds packages in-tree and will exhibit the same behaviour.

Closing as it is not an issue with build.

**Closed by layday** 2023-02-17 14:59 UTC
