### ISSUE TITLE
Failure to build a package within Docker with "No such file or directory: 'dist'"

### ISSUE THREAD

**Issue by hynek** [pypa/build#152] opened 2020-10-20 13:55 UTC
I know this is not super helpful because I can't share actual code with y'all, but I tried to replace a call of `python -m pep517.build .` to `python -m build` and it's failing when running within Docker in our CI (I can't reproduce it on my macOS laptop).

So this is what happens. The Python project to be built lives in `/src.` And `/_builder` is an virtualenv with the build script that (in this case) is trying to build itself so I can upload it to out PyPI:

<details>

```
2020-10-20T14:53:48.401970 $ /_builder/bin/python -m build
Looking in links: /tmp/tmpdzipf2ot
Requirement already satisfied: setuptools in /_builder/lib/python3.6/site-packages (40.6.2)
Requirement already satisfied: pip in /_builder/lib/python3.6/site-packages (18.1)
Looking in indexes: https://pypi.vm.ag/root/vrmd/+simple/
Collecting cython (from -r /tmp/build-reqs-6ot8x6so.txt (line 1))
  Downloading https://pypi.vm.ag/root/pypi/+f/57e/ad89128dee960/Cython-0.29.21-cp36-cp36m-manylinux1_x86_64.whl (2.0MB)
Requirement already satisfied: setuptools in /_builder/lib/python3.6/site-packages (from -r /tmp/build-reqs-6ot8x6so.txt (line 2)) (40.6.2)
Installing collected packages: cython
Successfully installed cython
running sdist
running egg_info
creating src/vrmd_builder.egg-info
writing src/vrmd_builder.egg-info/PKG-INFO
writing dependency_links to src/vrmd_builder.egg-info/dependency_links.txt
writing entry points to src/vrmd_builder.egg-info/entry_points.txt
writing requirements to src/vrmd_builder.egg-info/requires.txt
writing top-level names to src/vrmd_builder.egg-info/top_level.txt
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'deploy'
warning: no previously-included files found matching '*.ini'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching '*.yaml'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching 'Makefile'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching 'conftest.py'
warning: no previously-included files found matching 'feed_vault.py'
warning: no previously-included files found matching 'Procfile'
warning: no previously-included files found matching 'run-backend.sh'
warning: no previously-included files found matching 'Dockerfile'
warning: no previously-included files found matching 'Pipfile*'
warning: no previously-included files found matching '.dockerignore'
warning: no previously-included files found matching 'dev-vault_token'
warning: no files found matching '*.jinja2' under directory 'src'
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating vrmd-builder-32
creating vrmd-builder-32/src
creating vrmd-builder-32/src/builder
creating vrmd-builder-32/src/vrmd_builder.egg-info
copying files to vrmd-builder-32...
copying MANIFEST.in -> vrmd-builder-32
copying pyproject.toml -> vrmd-builder-32
copying setup.py -> vrmd-builder-32
copying src/builder/__init__.py -> vrmd-builder-32/src/builder
copying src/builder/__main__.py -> vrmd-builder-32/src/builder
copying src/builder/debs.py -> vrmd-builder-32/src/builder
copying src/builder/external.py -> vrmd-builder-32/src/builder
copying src/builder/go.py -> vrmd-builder-32/src/builder
copying src/builder/python.py -> vrmd-builder-32/src/builder
copying src/builder/rust.py -> vrmd-builder-32/src/builder
copying src/builder/utils.py -> vrmd-builder-32/src/builder
copying src/vrmd_builder.egg-info/PKG-INFO -> vrmd-builder-32/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/SOURCES.txt -> vrmd-builder-32/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/dependency_links.txt -> vrmd-builder-32/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/entry_points.txt -> vrmd-builder-32/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/not-zip-safe -> vrmd-builder-32/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/requires.txt -> vrmd-builder-32/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/top_level.txt -> vrmd-builder-32/src/vrmd_builder.egg-info
Writing vrmd-builder-32/setup.cfg
Creating tar archive
removing 'vrmd-builder-32' (and everything under it)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/builder
copying src/builder/external.py -> build/lib/builder
copying src/builder/go.py -> build/lib/builder
copying src/builder/__main__.py -> build/lib/builder
copying src/builder/debs.py -> build/lib/builder
copying src/builder/python.py -> build/lib/builder
copying src/builder/utils.py -> build/lib/builder
copying src/builder/rust.py -> build/lib/builder
copying src/builder/__init__.py -> build/lib/builder
running egg_info
writing src/vrmd_builder.egg-info/PKG-INFO
writing dependency_links to src/vrmd_builder.egg-info/dependency_links.txt
writing entry points to src/vrmd_builder.egg-info/entry_points.txt
writing requirements to src/vrmd_builder.egg-info/requires.txt
writing top-level names to src/vrmd_builder.egg-info/top_level.txt
reading manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'deploy'
warning: no previously-included files found matching '*.ini'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching '*.yaml'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching 'Makefile'
warning: no files found matching '*.jinja2' under directory 'src'
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/rust.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/go.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/__init__.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/debs.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/python.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/external.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/utils.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/__main__.py -> build/bdist.linux-x86_64/wheel/builder
running install_egg_info
Copying src/vrmd_builder.egg-info to build/bdist.linux-x86_64/wheel/vrmd_builder-32-py3.6.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/vrmd_builder-32.dist-info/WHEEL
creating 'dist/vrmd_builder-32-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'builder/__init__.py'
adding 'builder/__main__.py'
adding 'builder/debs.py'
adding 'builder/external.py'
adding 'builder/go.py'
adding 'builder/python.py'
adding 'builder/rust.py'
adding 'builder/utils.py'
adding 'vrmd_builder-32.dist-info/METADATA'
adding 'vrmd_builder-32.dist-info/WHEEL'
adding 'vrmd_builder-32.dist-info/entry_points.txt'
adding 'vrmd_builder-32.dist-info/top_level.txt'
adding 'vrmd_builder-32.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Traceback (most recent call last):
  File "/_builder/lib/python3.6/site-packages/pep517/_in_process.py", line 280, in <module>
    main()
  File "/_builder/lib/python3.6/site-packages/pep517/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/_builder/lib/python3.6/site-packages/pep517/_in_process.py", line 205, in build_wheel
    metadata_directory)
  File "/_builder/lib/python3.6/site-packages/setuptools/build_meta.py", line 161, in build_wheel
    shutil.copytree('dist', wheel_directory)
  File "/usr/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'dist'
Traceback (most recent call last):
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/_builder/bin/python', '/_builder/lib/python3.6/site-packages/pep517/_in_process.py', 'build_wheel', '/tmp/tmpu55eg9wm']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/_builder/lib/python3.6/site-packages/build/__init__.py", line 215, in build
    raise BuildBackendException('Backend operation failed: {}'.format(e))
build.BuildBackendException: Backend operation failed: Command '['/_builder/bin/python', '/_builder/lib/python3.6/site-packages/pep517/_in_process.py', 'build_wheel', '/tmp/tmpu55eg9wm']' returned non-zero exit status 1.

ERROR Backend operation failed: Command '['/_builder/bin/python', '/_builder/lib/python3.6/site-packages/pep517/_in_process.py', 'build_wheel', '/tmp/tmpu55eg9wm']' returned non-zero exit status 1.
no output
Execution failed with return code 1.
```

</details>

If I do an `ls` afterwards, there indeed is no `dist` directory in the current working directory (not in `/` which I checked just in case).

Unfortunately it's really hard to debug, since each turnaround takes more than 10 minutes. :|

For the record, this is the same output for pep517.build:

<details>

```
2020-10-20T15:49:42.116243 $ /_builder/bin/python -m pep517.build .
running egg_info
creating src/vrmd_builder.egg-info
writing src/vrmd_builder.egg-info/PKG-INFO
writing dependency_links to src/vrmd_builder.egg-info/dependency_links.txt
writing entry points to src/vrmd_builder.egg-info/entry_points.txt
writing requirements to src/vrmd_builder.egg-info/requires.txt
writing top-level names to src/vrmd_builder.egg-info/top_level.txt
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'deploy'
warning: no previously-included files found matching '*.ini'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching '*.yaml'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching 'Makefile'
warning: no files found matching '*.jinja2' under directory 'src'
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
running sdist
running egg_info
writing src/vrmd_builder.egg-info/PKG-INFO
writing dependency_links to src/vrmd_builder.egg-info/dependency_links.txt
writing entry points to src/vrmd_builder.egg-info/entry_points.txt
writing requirements to src/vrmd_builder.egg-info/requires.txt
writing top-level names to src/vrmd_builder.egg-info/top_level.txt
reading manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'deploy'
warning: no previously-included files found matching '*.ini'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching '*.yaml'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching 'Makefile'

warning: no files found matching '*.jinja2' under directory 'src'
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating vrmd-builder-35
creating vrmd-builder-35/src
creating vrmd-builder-35/src/builder
creating vrmd-builder-35/src/vrmd_builder.egg-info
copying files to vrmd-builder-35...
copying MANIFEST.in -> vrmd-builder-35
copying pyproject.toml -> vrmd-builder-35
copying setup.py -> vrmd-builder-35
copying src/builder/__init__.py -> vrmd-builder-35/src/builder
copying src/builder/__main__.py -> vrmd-builder-35/src/builder
copying src/builder/debs.py -> vrmd-builder-35/src/builder
copying src/builder/external.py -> vrmd-builder-35/src/builder
copying src/builder/go.py -> vrmd-builder-35/src/builder
copying src/builder/python.py -> vrmd-builder-35/src/builder
copying src/builder/rust.py -> vrmd-builder-35/src/builder
copying src/builder/utils.py -> vrmd-builder-35/src/builder
copying src/vrmd_builder.egg-info/PKG-INFO -> vrmd-builder-35/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/SOURCES.txt -> vrmd-builder-35/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/dependency_links.txt -> vrmd-builder-35/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/entry_points.txt -> vrmd-builder-35/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/not-zip-safe -> vrmd-builder-35/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/requires.txt -> vrmd-builder-35/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/top_level.txt -> vrmd-builder-35/src/vrmd_builder.egg-info
Writing vrmd-builder-35/setup.cfg
Creating tar archive
removing 'vrmd-builder-35' (and everything under it)
running egg_info
writing src/vrmd_builder.egg-info/PKG-INFO
writing dependency_links to src/vrmd_builder.egg-info/dependency_links.txt
writing entry points to src/vrmd_builder.egg-info/entry_points.txt
writing requirements to src/vrmd_builder.egg-info/requires.txt
writing top-level names to src/vrmd_builder.egg-info/top_level.txt
reading manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'deploy'
warning: no previously-included files found matching '*.ini'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching '*.yaml'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching 'Makefile'
warning: no files found matching '*.jinja2' under directory 'src'
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/builder
copying src/builder/external.py -> build/lib/builder
copying src/builder/go.py -> build/lib/builder
copying src/builder/__main__.py -> build/lib/builder
copying src/builder/debs.py -> build/lib/builder
copying src/builder/python.py -> build/lib/builder
copying src/builder/utils.py -> build/lib/builder
copying src/builder/rust.py -> build/lib/builder
copying src/builder/__init__.py -> build/lib/builder
running egg_info
writing src/vrmd_builder.egg-info/PKG-INFO
writing dependency_links to src/vrmd_builder.egg-info/dependency_links.txt
writing entry points to src/vrmd_builder.egg-info/entry_points.txt
writing requirements to src/vrmd_builder.egg-info/requires.txt
writing top-level names to src/vrmd_builder.egg-info/top_level.txt
reading manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'deploy'
warning: no previously-included files found matching '*.ini'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching '*.yaml'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching 'Makefile'
warning: no files found matching '*.jinja2' under directory 'src'
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/external.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/__main__.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/go.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/rust.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/utils.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/python.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/__init__.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/debs.py -> build/bdist.linux-x86_64/wheel/builder
running install_egg_info
Copying src/vrmd_builder.egg-info to build/bdist.linux-x86_64/wheel/vrmd_builder-35-py3.6.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/vrmd_builder-35.dist-info/WHEEL
creating '/tmp/tmpoxbatu12/tmpgznfop1d/vrmd_builder-35-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'builder/__init__.py'
adding 'builder/__main__.py'
adding 'builder/debs.py'
adding 'builder/external.py'
adding 'builder/go.py'
adding 'builder/python.py'
adding 'builder/rust.py'
adding 'builder/utils.py'
adding 'vrmd_builder-35.dist-info/METADATA'
adding 'vrmd_builder-35.dist-info/WHEEL'
adding 'vrmd_builder-35.dist-info/entry_points.txt'
adding 'vrmd_builder-35.dist-info/top_level.txt'
adding 'vrmd_builder-35.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
```

</details>

---

Please don't remove `pep517.build` until this works. 🙈

**Comment by FFY00** [comment] 2020-10-20 14:01
Should be the same as #69.

The code is in https://github.com/pypa/build/blob/784f8cf1a883d3bbbbe5cdf8cef1b5bcfb832130/src/build/__init__.py#L187.

I am not really sure why this is happening, we take the abspath of outdir before calling the hook (which happens in a different working directory).

I will try to look at this afternoon or tomorrow.

**Comment by hynek** [comment] 2020-10-20 14:02
If it helps: I tried passing both `.` and `str(Path(".").absolute())` as arguments to no avail.

**Comment by hynek** [comment] 2020-10-20 14:51
After reading #69, I've also tried to create the dist directory myself and pass the absolute path as `-o` which also didn't help: `/_builder/bin/python -m build -o /src/dist /src` this suggests that the mkdir code path is not the problem but that it looks in the wrong place for some reason.

**Comment by gaborbernat** [comment] 2020-10-20 15:01
To me sounds like:
- someone removes the dist folder within your pipeline
- someone changes the cwd (can you print the cwd from within your setup.py?)

**Comment by hynek** [comment] 2020-10-20 15:19
- I verified that the empty dist folder exists after `python -m build`.
- Unfortunately I cannot do this because my build scripts rely on the output of the `setup.py`. I don't find it very plausible tho because my setup.py is super plain:

```python
from setuptools import find_packages, setup


NAME = "vrmd-builder"
REQUIRES = [
    "attrs",
    "boltons",
    "click",
    "devpi-client",
    "glom",
    "httpx[http2]",
    "pyyaml",
    "toml",
    "wheel",
    "virtualenv>20.0",
    "yarl",
]
EXTRAS_REQUIRE = {"tests": ["coverage", "mypy", "pytest"]}
EXTRAS_REQUIRE["dev"] = ["flake8", "ipython", "pdbpp"] + EXTRAS_REQUIRE[
    "tests"
]
ENTRY_POINTS = {"console_scripts": ["build = builder.__main__:cli"]}

###############################################################################


if __name__ == "__main__":
    setup(
        name=NAME,
        version="0",
        packages=find_packages(where="src"),
        package_dir={"": "src"},
        classifiers=["Private :: Do Not Upload"],
        include_package_data=True,
        zip_safe=False,
        install_requires=REQUIRES,
        extras_require=EXTRAS_REQUIRE,
        entry_points=ENTRY_POINTS,
    )
```

---

As for both: literally replacing `python -m build` by `python -m pep517.build` fixes it, so… `¯\_(ツ)_/¯`

**Comment by pganssle** [comment] 2020-10-20 15:41
Just something to note:

```
Requirement already satisfied: setuptools in /_builder/lib/python3.6/site-packages (40.6.2)
Requirement already satisfied: pip in /_builder/lib/python3.6/site-packages (18.1)
```

@hynek Does it help to do `pip install -U pip setuptools` beforehand? It _shouldn't_, but if `_builder` is a virtualenv you are probably hitting #97 (which is fixed in master but not released).

I also think the problem you are hitting is #108, so the short term fix is to `pip install -U setuptools`, and the longer term fix is to use `build > 0.0.4`.

**Comment by hynek** [comment] 2020-10-20 17:01
Looks like Paul is right:

<details>

```
2020-10-20T18:57:32.094047 $ /_builder/bin/python -m build -o /src/dist /src
Looking in links: /tmp/tmpm8xfuxob
Requirement already satisfied: setuptools in /_builder/lib/python3.6/site-packages (50.3.2)
Requirement already satisfied: pip in /_builder/lib/python3.6/site-packages (20.2.4)
Looking in indexes: https://pypi.vm.ag/root/vrmd/+simple/
Collecting cython
  Downloading https://pypi.vm.ag/root/pypi/%2Bf/57e/ad89128dee960/Cython-0.29.21-cp36-cp36m-manylinux1_x86_64.whl (2.0 MB)
Requirement already satisfied: setuptools in /_builder/lib/python3.6/site-packages (from -r /tmp/build-reqs-2ym_vj_a.txt (line 2)) (50.3.2)
Installing collected packages: cython
Successfully installed cython
running sdist
running egg_info
creating src/vrmd_builder.egg-info
writing src/vrmd_builder.egg-info/PKG-INFO
writing dependency_links to src/vrmd_builder.egg-info/dependency_links.txt
writing entry points to src/vrmd_builder.egg-info/entry_points.txt
writing requirements to src/vrmd_builder.egg-info/requires.txt
writing top-level names to src/vrmd_builder.egg-info/top_level.txt
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'deploy'
warning: no previously-included files found matching '*.ini'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching '*.yaml'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching 'Makefile'
warning: no previously-included files found matching 'conftest.py'
warning: no files found matching '*.jinja2' under directory 'src'
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

creating vrmd-builder-43
creating vrmd-builder-43/src
creating vrmd-builder-43/src/builder
creating vrmd-builder-43/src/vrmd_builder.egg-info
copying files to vrmd-builder-43...
copying MANIFEST.in -> vrmd-builder-43
copying pyproject.toml -> vrmd-builder-43
copying setup.py -> vrmd-builder-43
copying src/builder/__init__.py -> vrmd-builder-43/src/builder
copying src/builder/__main__.py -> vrmd-builder-43/src/builder
copying src/builder/debs.py -> vrmd-builder-43/src/builder
copying src/builder/external.py -> vrmd-builder-43/src/builder
copying src/builder/go.py -> vrmd-builder-43/src/builder
copying src/builder/python.py -> vrmd-builder-43/src/builder
copying src/builder/rust.py -> vrmd-builder-43/src/builder
copying src/builder/utils.py -> vrmd-builder-43/src/builder
copying src/vrmd_builder.egg-info/PKG-INFO -> vrmd-builder-43/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/SOURCES.txt -> vrmd-builder-43/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/dependency_links.txt -> vrmd-builder-43/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/entry_points.txt -> vrmd-builder-43/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/not-zip-safe -> vrmd-builder-43/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/requires.txt -> vrmd-builder-43/src/vrmd_builder.egg-info
copying src/vrmd_builder.egg-info/top_level.txt -> vrmd-builder-43/src/vrmd_builder.egg-info
Writing vrmd-builder-43/setup.cfg
Creating tar archive
removing 'vrmd-builder-43' (and everything under it)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/builder
copying src/builder/external.py -> build/lib/builder
copying src/builder/go.py -> build/lib/builder
copying src/builder/__main__.py -> build/lib/builder
copying src/builder/debs.py -> build/lib/builder
copying src/builder/python.py -> build/lib/builder
copying src/builder/utils.py -> build/lib/builder
copying src/builder/rust.py -> build/lib/builder
copying src/builder/__init__.py -> build/lib/builder
running egg_info
writing src/vrmd_builder.egg-info/PKG-INFO
writing dependency_links to src/vrmd_builder.egg-info/dependency_links.txt
writing entry points to src/vrmd_builder.egg-info/entry_points.txt
writing requirements to src/vrmd_builder.egg-info/requires.txt
writing top-level names to src/vrmd_builder.egg-info/top_level.txt
reading manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tests'
no previously-included directories found matching 'deploy'
warning: no previously-included files found matching '*.ini'
warning: no previously-included files found matching '*.yml'
warning: no previously-included files found matching '*.yaml'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching 'Makefile'
warning: no previously-included files found matching 'conftest.py'
warning: no files found matching '*.jinja2' under directory 'src'
writing manifest file 'src/vrmd_builder.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/debs.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/go.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/utils.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/__init__.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/python.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/rust.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/__main__.py -> build/bdist.linux-x86_64/wheel/builder
copying build/lib/builder/external.py -> build/bdist.linux-x86_64/wheel/builder
running install_egg_info
Copying src/vrmd_builder.egg-info to build/bdist.linux-x86_64/wheel/vrmd_builder-43-py3.6.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/vrmd_builder-43.dist-info/WHEEL
creating '/src/dist/tmpzrxgz2j5/vrmd_builder-43-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'builder/__init__.py'
adding 'builder/__main__.py'
adding 'builder/debs.py'
adding 'builder/external.py'
adding 'builder/go.py'
adding 'builder/python.py'
adding 'builder/rust.py'
adding 'builder/utils.py'
adding 'vrmd_builder-43.dist-info/METADATA'
adding 'vrmd_builder-43.dist-info/WHEEL'
adding 'vrmd_builder-43.dist-info/entry_points.txt'
adding 'vrmd_builder-43.dist-info/top_level.txt'
adding 'vrmd_builder-43.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
```

</details>

Does this mean that everything that is hitting me is already part of other tickets and this can be closed?

**Comment by pganssle** [comment] 2020-10-20 17:10
> Does this mean that everything that is hitting me is already part of other tickets and this can be closed?

Yeah, I think this is actually an exact duplicate of #108. Closing. Hopefully we will get a new release out soon that includes the latest fixes.

Thanks for being an early adopter, sorry for the rough edges. :smile:

**Closed by pganssle** 2020-10-20 17:10 UTC
