### ISSUE TITLE
Double requirement error if build-backend missing

### ISSUE THREAD

**Issue by henryiii** [pypa/build#107] opened 2020-09-28 21:44 UTC
I have the following pyproject.toml:

```toml
[build-system]
requires = ["wheel", "setuptools>=42", "setuptools_scm[toml]>=3.4"]
```

Build fails with:

```
Looking in links: /tmp/tmpu9cyr1oc
Processing /tmp/tmpu9cyr1oc/setuptools-47.1.0-py3-none-any.whl
Processing /tmp/tmpu9cyr1oc/pip-20.1.1-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip setuptools
ERROR: Double requirement given: setuptools>=42 (from -r /tmp/build-reqs-akrau6fv.txt (line 2)) (already in setuptools>=40.8.0 (from -r /tmp/build-reqs-akrau6fv.txt (line 1)), name='setuptools')
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.5/x64/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/build/__main__.py", line 176, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/build/__main__.py", line 168, in main
    build(args.srcdir, args.outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/build/__main__.py", line 80, in build
    _build_in_isolated_env(builder, outdir, distributions)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/build/__main__.py", line 45, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/build/env.py", line 176, in install
    subprocess.check_call(cmd)
  File "/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.8.5/x64/bin/python', '-m', 'pip', 'install', '--prefix', '/tmp/build-env-6o04yjl_', '-r', '/tmp/build-reqs-akrau6fv.txt']' returned non-zero exit status 1.
```

However, there is a missing line - and adding it fixed the problem:

```toml
build-backend = "setuptools.build_meta"
```

a) Is it possible to improve the error message and b) should this error be happening anyway? It seems to be trying to recursively produce all the requirements manually and put then into a requirements.txt-like file, which then collide?

**Comment by FFY00** [comment] 2020-09-28 21:48
This happens because pip can't resolve multiple dependencies right now, that will change in the next release. For now, you can set `PIP_USE_FEATURE=2020-resolver` to force pip to use the new dependency resolver.

I deliberately choose to not implement a dependency resolver as it is not trivial and pip is getting one anyway.

**Comment by FFY00** [comment] 2020-09-28 21:51
Hum sorry, seems like the pip version you are using is 20.1 and `PIP_USE_FEATURE=2020-resolver` is only available in 20.2.

Perhaps `ensurepip`, which is what we use to get pip into the environment, copies the system pip. Try upgrading it.

**Comment by FFY00** [comment] 2020-09-28 21:53
But I would definitely recommend to explicitly set the build backend, otherwise `setuptools.build_meta:__legacy__` will be used, you probably want `setuptools.build_meta`.

**Comment by pganssle** [comment] 2020-09-30 14:01
Regardless of resolving, I think the issue here is [this](https://github.com/FFY00/python-build/blob/b805ff79227d7d72057068e292ab10af6861fcb6/src/build/__init__.py#L153), we inject the requirements for the default build-backend into `requires` if `build-backend` is not specified.

I think we should probably do one of the following things here:

1. Don't inject the requirements for the default backend into `requires` if `requires` is specified, since people are probably not expecting their `requires` to get messed with in the first place. I assume that this is not a requirement of PEP 518.
2. Do extremely minimal resolving for the trivial case by checking if each of the default backend requirements are in the existing `requires`, and taking a union of the bounds — we can explicitly throw an error in the case of a null set or anything that's too complicated to resolve properly.

I'm in favor of option 1 here, because I definitely don't expect `build` to be injecting requirements for the default backend on top of my existing requirements. Option 2 will make more stuff work "out of the box", but I don't know how much that matters to me, since it doesn't seem like a big deal to ask people to get their build metadata right _given that they've already added it_.

**Comment by pganssle** [comment] 2020-09-30 14:05
As a data point, `pip`'s current behavior is to treat `build-system.requires` as complete even when the `build-system.build-backend` key is missing.

A project with the following `setup.cfg`:

```ini
[metadata]
name = project
version = 0.0.1
```

And the following `pyproject.toml`:

```toml
[build-system]
requires = []
```

Will fail when you do `pip install .`, but will succeed if you do `python -m build`. We should probably fail as well (particularly since this could easily lead to a situation where `python -m build` is generating source distributions that `pip` cannot install).

**Comment by FFY00** [comment] 2020-09-30 14:17
> Don't inject the requirements for the default backend into `requires` if `requires` is specified, since people are probably not expecting their `requires` to get messed with in the first place. I assume that this is not a requirement of PEP 518.

Right. We should probably also add a message saying that we defaulted to `setuptools.build_meta.__legacy__` if no backend is specified, to make things easier to debug for people who have not read the whole PEP 517.

If we choose not to inject requirements I think it would be better to just disallow specifying `requires` when `build-backend` is not set.

Having duplicated requirements still is possible, and that will only be fixed with pip 20.3.

**Comment by henryiii** [comment] 2020-09-30 14:26
> I think it would be better to just disallow specifying

Personally, I would prefer consistency with pip. `requires = ["wheel", "setuptools>=42", "setuptools_scm[toml]>=3.4"]` builds with pip since no extra requirements are injected, so you don't have the setuptools clash.

A message saying "please specify a backend" would be not a bad idea, though, I think. :) (I rather wish the PEP had enforced that)

**Comment by pganssle** [comment] 2020-09-30 14:28
> If we choose not to inject requirements I think it would be better to just disallow specifying `requires` when `build-backend` is not set.

I disagree with this — there are a lot of packages out there that started specifying PEP 518 requirements before adding `build-backend`, partially because PEP 518 was implemented in `pip` first and partially because PEP 518 gives immediate added value if you have a build-time dependency like Cython. A lot of people didn't want to specify `build-backend = 'setuptools.build_meta'` because it opts them into a slightly different build setup, so they just leave it blank.

As much as I'd like to force people to specify their build backend, we'll have a lot of packages out there without `build-backend` explicitly specified, and distros will need to carry patches to `pyproject.toml` if they want to use `build` as their canonical way to build distro packages.

I think the best thing to do would be to do what `pip` is doing:

- If `requires` is specified, it is always used unmodified.
- If `requires` is unspecified and `build-backend` is unspecified, use the defaults.
- If `build-system` is present without a `requires`, throw an error (it is mandatory in PEP 518).

> Having duplicated requirements still is possible, and that will only be fixed with pip 20.3.

I don't really understand this point. The duplicated requirement here is being injected _by us_. If the end user specifies duplicated requirements, that is their problem. `pip` will handle duplicated _transitive_ dependencies gracefully, just not direct dependencies.

**Comment by FFY00** [comment] 2020-09-30 14:44
> I disagree with this — there are a lot of packages out there that started specifying PEP 518 requirements before adding `build-backend`, partially because PEP 518 was implemented in `pip` first and partially because PEP 518 gives immediate added value if you have a build-time dependency like Cython. A lot of people didn't want to specify `build-backend = 'setuptools.build_meta'` because it opts them into a slightly different build setup, so they just leave it blank.

Okay, I undertand.

> As much as I'd like to force people to specify their build backend, we'll have a lot of packages out there without `build-backend` explicitly specified, and distros will need to carry patches to `pyproject.toml` if they want to use `build` as their canonical way to build distro packages.

Well, distributions could still use `setup.py` in those cases. When the project drops `setup.py` they will likely have to use python-build anyway and would fix ths. But the points you made above make sense.

> I don't really understand this point. The duplicated requirement here is being injected _by us_. If the end user specifies duplicated requirements, that is their problem. `pip` will handle duplicated _transitive_ dependencies gracefully, just not direct dependencies.

Nor PEP 518 or 517 makes restrictions regarding the requirements. Although for `build-system.requires` it might not really be a problem, since it is directly specified by a user and can be easily fixed, `get_requires_for_build_{sdist,wheel}` could potentially be problematic as a build systems could for eg. generate this list automatically. Since duplicated requirements are not forbidden, I think they should be something to keep in mind.

**Comment by pganssle** [comment] 2020-09-30 15:05
> Nor PEP 518 or 517 makes restrictions regarding the requirements.

You mean neither of them restricts whether you can specify the same thing twice?

That's true, but again it's not really our problem. The minimum we can do is to not exacerbate the situation by injecting requirements that the user never specified. I think it's reasonable to specify defaults, but not to modify explicitly specified fields.

**Comment by FFY00** [comment] 2020-09-30 15:08
Eh, we still need to install them, so we need to make sure that works. I was just pointing out that the core issue here, pip not being able to install duplicated requirements, is still there. It was not an argument in favor of keeping injecting requirements.

**Comment by pelson** [comment] 2020-10-06 15:21
This cropped up for me today with a very similar ``pyproject.toml`` to the OP. There is no doubt that the error message is fairly obscure and could be improved if the existing behaviour is planned to remain in this way.

However, IMO, if ``python-build`` wants to inject requirements into a build it should do so with a little care for what has already been defined in the build requirements. The basic tools to do this are already in ``packaging`` (already a dependency) with a little creativity (which should perhaps belong in ``packaging`` in the first place):


```
import typing

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


def join_requirement(req1: Requirement, req2: Requirement) -> Requirement:
    """
    Join together two requirement specifications for the same package name by
    evaluating the markers (if they exist) against the current Python process.

    """
    if req2.marker and not req2.marker.evaluate():
        # No matter what req2 says, it evaluates false, so it doesn't influence
        # the final spec. Note it is entirely possible that req1 doesn't
        # evaluate true either, but we let downstream tools deal with the
        # marker handling.
        return req1
    elif req1.marker and not req1.marker.evaluate():
        return req2
    else:
        spec = r1.specifier & r2.specifier
        extras = ','.join(f'"{name}"' for name in r1.extras | r2.extras)
        return Requirement(f"{req1.name}[{extras}]{spec}")


def join_requirements(
        requirements1: typing.Iterable[Requirement],
        requirements2: typing.Iterable[Requirement]
) -> typing.List[Requirement]:
    """
    Given two iterables of Requirements, merge together those which overlap.

    """
    r1_lookup = {canonicalize_name(req.name): req for req in requirements1}
    r2_lookup = {canonicalize_name(req.name): req for req in requirements2}

    result = []
    for name, req in r1_lookup.items():
        if name in r2_lookup:
            req = join_requirement(req, r2_lookup.pop(name))
        result.append(req)
    # We've been mutating r2_lookup, so anything that's left doesn't collide
    # with req1 and should just be be added.
    result.extend(r2_lookup)
    return result
```

For example:

```
>>> requirements = ['setuptools>=42.2 ; python_version<"3.0"', 'wheel']
>>> other = ['setuptools>=41.2', 'another']
>>> join_requirements(
...     [Requirement(req) for req in requirements],
...     [Requirement(req) for req in other]
... )
[<Requirement('setuptools>=41.2')>, <Requirement('wheel')>, 'another']
```

To summarise, I think there are a number of options for addressing this issue:

 1. Do nothing (i.e. await pip to handle duplicate requirements properly)
 2. Improve the error message. Likely by catching the fact that the user has already set some build requirements but not defined the backend.
 3. Safely inject the requirements of the default ``build-backend`` (e.g. the code above) if the user has specified requirements but not the backend.

There is advice in pypa repositories (e.g. https://github.com/pypa/setuptools_scm#pyprojecttoml-usage) which provide examples which are missing the build backend in ``pyproject.toml`` and as a result there will be many examples in the wild which see the same message as the OP when invoking ``python-build``. Personally I find it a shame that people's first impression of ``python-build`` would be that, particularly when considering that ``pip wheel --no-deps`` will build a project with such a ``pyproject.toml``. 

If any help is needed implementing it I'd be happy to contribute in any way I can.

**Comment by pganssle** [comment] 2020-10-07 19:23
@FFY00 Did you mean to assign this `wontfix`? I thought we were going to just drop the requirements injection thing, since it's the cause of the bug, unnecessary, not in keeping with the spec and inconsistent with what `pip` does.

**Closed** 2020-11-01 09:33 UTC
Labels: bug, wontfix
