### ISSUE TITLE
'typing-extensions>=3.6.4; python_version < "3.8"' distribution was not found and is required by importlib-metadata

### ISSUE THREAD

**Issue by williamjmorenor** [pypa/build#201] opened 2020-12-31 15:38 UTC
Hello, I am not sure if this issue comes from build it self but when testing with alpha version of python 3.10 I found this:

pkg_resources.DistributionNotFound: The 'typing-extensions>=3.6.4; python_version < "3.8"' distribution was not found and is required by importlib-metadata

https://github.com/cacao-accounting/cacao-accounting/runs/1630729986?check_suite_focus=true

**Comment by FFY00** [comment] 2020-12-31 15:59
I don't think this is our issue as it is the backend that is failing. It should be either setuptools or pkg_resources.

**Comment by FFY00** [comment] 2020-12-31 16:04
Sorry, it is not the backend that is failing, it's twine.

**Comment by uranusjr** [comment] 2020-12-31 16:18
Twine is only failing because its runtime dependencies are not satisfied. But either way this is not related in any way to `build`, which only deals with build dependencies.

**Comment by FFY00** [comment] 2020-12-31 16:19
How is the dependency not satisfied if it is running on Python 3.10 and we have the `python_version < "3.8"` marker?

**Comment by uranusjr** [comment] 2020-12-31 16:56
I have no idea, but that should be a problem for setuptools. (Maybe it's comparing versions wrong and thinking `'3.10' < '3.8'`)

**Comment by FFY00** [comment] 2020-12-31 21:38
Then the problem is not unsatisfied runtime dependencies, its runtime dependencies not being properly verified :blush:

**Comment by bhrutledge** [comment] 2021-01-02 20:32
I believe this can be closed, as this can be resolved by upgrading to `setuptools>=49.0.0`, as detailed at https://github.com/pypa/twine/issues/724#issuecomment-753503728.

**Closed** 2021-01-02 20:40 UTC
Labels: bug, needs info
