### ISSUE TITLE
ERROR Source /tmp/ie/build-via-sdist-9bdxaz8y/pypackage-0.1.0.... does not appear to be a Python project: no pyproject.toml or setup.py

### ISSUE THREAD

**Issue by ashrauma** [pypa/build#349] opened 2021-09-13 17:22 UTC
While executing `python -m build`

Logs:
```
...
Creating tar archive
removing 'pypackage-0.1.0' (and everything under it)
ERROR Source /tmp/ie/build-via-sdist-9bdxaz8y/pypackage-0.1.0 does not appear to be a Python project: no pyproject.toml or setup.py
...
```

Python version: 3.7.5
build version: 0.6.0

There is definitely setup.py, setup.cfg and pyproject.toml.

**Comment by FFY00** [comment] 2021-09-13 17:44
Can you show the source of the package you are trying to build? It seems that it does not contain a `pyproject.toml` or `setup.py` file, which means it is not a valid Python package source.

**Comment by ashrauma** [comment] 2021-09-13 17:51
pyproject.toml
```
[build-system]
requires = ["setuptools", "wheel"]
```

setup.py
```
from setuptools import setup

setup(
   name='pypackage',
   description='blah blah blah',
   author='ashrauma',
   author_email='ashrauma@company.com',
   packages=['package1'],
   install_requires=[],
)
```

setup.cfg
```
[metadata]
version = file: VERSION.txt
```

VERSION.txt
```
0.1.0
```

MANIFEST.in
```
include VERSION.txt
```

**Comment by FFY00** [comment] 2021-09-13 17:54
Is this inside a directory? By default `python -m build` will look for a package in the current directory. If it's not in the current directory, you need pass the directory which contains the `pyproject.toml` as an argument (eg. `python -m build path/to/source` -- `path/to/source/pyproject.toml` should exist).

**Comment by ashrauma** [comment] 2021-09-13 17:57
Yes all those files are in current directory from where `python -m build` is run.

**Comment by ashrauma** [comment] 2021-09-13 17:59
Is there is a way to --trace/--debug/--verbose it?

**Comment by FFY00** [comment] 2021-09-13 18:07
There isn't. Can you put the package in a git repo so that I can reproduce?

**Comment by FFY00** [comment] 2021-09-13 18:11
Using the details you provided I can't reproduce.

```
$ tree
.
├── MANIFEST.in
├── package1
│   └── __init__.py
├── pyproject.toml
├── setup.cfg
├── setup.py
└── VERSION.txt

1 directory, 6 files
```

```
$ python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools, wheel)
* Getting dependencies for sdist...
running egg_info
writing pypackage.egg-info/PKG-INFO
writing dependency_links to pypackage.egg-info/dependency_links.txt
writing top-level names to pypackage.egg-info/top_level.txt
reading manifest file 'pypackage.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pypackage.egg-info/SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing pypackage.egg-info/PKG-INFO
writing dependency_links to pypackage.egg-info/dependency_links.txt
writing top-level names to pypackage.egg-info/top_level.txt
reading manifest file 'pypackage.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pypackage.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt, README.md

running check
warning: check: missing required meta-data: url

creating pypackage-0.1.0
creating pypackage-0.1.0/package1
creating pypackage-0.1.0/pypackage.egg-info
copying files to pypackage-0.1.0...
copying MANIFEST.in -> pypackage-0.1.0
copying VERSION.txt -> pypackage-0.1.0
copying pyproject.toml -> pypackage-0.1.0
copying setup.cfg -> pypackage-0.1.0
copying setup.py -> pypackage-0.1.0
copying package1/__init__.py -> pypackage-0.1.0/package1
copying pypackage.egg-info/PKG-INFO -> pypackage-0.1.0/pypackage.egg-info
copying pypackage.egg-info/SOURCES.txt -> pypackage-0.1.0/pypackage.egg-info
copying pypackage.egg-info/dependency_links.txt -> pypackage-0.1.0/pypackage.egg-info
copying pypackage.egg-info/top_level.txt -> pypackage-0.1.0/pypackage.egg-info
Writing pypackage-0.1.0/setup.cfg
Creating tar archive
removing 'pypackage-0.1.0' (and everything under it)
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools, wheel)
* Getting dependencies for wheel...
running egg_info
writing pypackage.egg-info/PKG-INFO
writing dependency_links to pypackage.egg-info/dependency_links.txt
writing top-level names to pypackage.egg-info/top_level.txt
reading manifest file 'pypackage.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pypackage.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/package1
copying package1/__init__.py -> build/lib/package1
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/package1
copying build/lib/package1/__init__.py -> build/bdist.linux-x86_64/wheel/package1
running install_egg_info
running egg_info
writing pypackage.egg-info/PKG-INFO
writing dependency_links to pypackage.egg-info/dependency_links.txt
writing top-level names to pypackage.egg-info/top_level.txt
reading manifest file 'pypackage.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pypackage.egg-info/SOURCES.txt'
Copying pypackage.egg-info to build/bdist.linux-x86_64/wheel/pypackage-0.1.0-py3.9.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/pypackage-0.1.0.dist-info/WHEEL
creating '/home/anubis/test/build-349/dist/tmpklino6pc/pypackage-0.1.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'package1/__init__.py'
adding 'pypackage-0.1.0.dist-info/METADATA'
adding 'pypackage-0.1.0.dist-info/WHEEL'
adding 'pypackage-0.1.0.dist-info/top_level.txt'
adding 'pypackage-0.1.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built pypackage-0.1.0.tar.gz and pypackage-0.1.0-py3-none-any.whl
```

```
$ python -m build --version
build 0.6.0 (/usr/lib/python3.9/site-packages/build)
```

**Comment by ashrauma** [comment] 2021-09-13 18:31
Oh thank you. You are right when I create a new pypackage, it works fine. I will try to debug this further and report back.

**Comment by FFY00** [comment] 2021-09-21 15:58
Closing this for now, please re-open if you are able to create a reproducible.

**Closed by FFY00** 2021-09-21 15:58 UTC
