### ISSUE TITLE
error from pypa build

### ISSUE THREAD

**Issue by MrBitBucket** [pypa/build#341] opened 2021-08-06 10:35 UTC
I'm building a pure python wheel in a python3.9 virtualenv.

If I use python setup.py bdist_wheel I do get a wheel named

rlextra-3.6.0-py3-none-any.whl

I'm trying out building a modern python 3 only wheel so I followed instructions here

https://packaging.python.org/tutorials/packaging-projects/#creating-the-package-files

and see the error below which is not very informative. Any ideas of what's wrong? I still get the error even after upgrading pip so I don't think that is the problem.

```
> (.py39) user@pc:~/devel/reportlab/REPOS/rlextra
> $ pip install build
> Collecting build
>   Downloading build-0.5.1-py2.py3-none-any.whl (15 kB)
> Collecting pep517>=0.9.1
> ..........
> Installing collected packages: tomli, pyparsing, toml, pep517, packaging, build
> Successfully installed build-0.5.1 packaging-21.0 pep517-0.11.0 pyparsing-2.4.7 toml-0.10.2 tomli-1.2.0
> WARNING: You are using pip version 21.1.3; however, version 21.2.2 is available.
> You should consider upgrading via the '/home/user/devel/reportlab/.py39/bin/python39 -m pip install --upgrade pip' command.
> (.py39) user@pc:~/devel/reportlab/REPOS/rlextra
> $ ls
> build  dist  docs  examples  LICENSE.txt  README.txt  setup.cfg  setup.py  src  tests  tmp
> (.py39) user@pc:~/devel/reportlab/REPOS/rlextra
> $ python -m build --wheel
> Traceback (most recent call last):
>   File "/home/user/devel/reportlab/.py39/lib/python3.9/site-packages/build/__main__.py", line 302, in main
>     build_call(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependency_check)
>   File "/home/user/devel/reportlab/.py39/lib/python3.9/site-packages/build/__main__.py", line 145, in build_package
>     _build(isolation, builder, outdir, distribution, config_settings, skip_dependency_check)
>   File "/home/user/devel/reportlab/.py39/lib/python3.9/site-packages/build/__main__.py", line 101, in _build
>     return _build_in_isolated_env(builder, outdir, distribution, config_settings)
>   File "/home/user/devel/reportlab/.py39/lib/python3.9/site-packages/build/__main__.py", line 77, in _build_in_isolated_env
>     with IsolatedEnvBuilder() as env:
>   File "/home/user/devel/reportlab/.py39/lib/python3.9/site-packages/build/env.py", line 92, in __enter__
>     executable, scripts_dir = _create_isolated_env_venv(self._path)
>   File "/home/user/devel/reportlab/.py39/lib/python3.9/site-packages/build/env.py", line 221, in _create_isolated_env_venv
>     pip_distribution = next(iter(metadata.distributions(name='pip', path=[purelib])))
> StopIteration
>
> ERROR
> (.py39) user@pc:~/devel/reportlab/REPOS/rlextra
```

thanks for any assistance 
--
Robin Becker

**Comment by domdfcoding** [comment] 2021-08-06 11:28
Can you try again after installing `build[virtualenv]`, which uses virtualenv rather than Python's built-in venv module?

Can you also try creating and activating a virtual environment with ``python3 -m venv venv && source venv/bin/activate``, and see if pip is present in the virtual environment with ``which pip`` (should be `./venv/bin/pip` and not something like `/usr/local/bin/pip`).

-----

I haven't been able to reproduce this with other repositories, so I'm leaning towards this being a bug in Python (or your particular installation of it).

**Comment by gaborbernat** [comment] 2021-08-06 12:29
I think the problem here is that we're only looking for pip in the purelib path, however in this case it's installed in a different location on sys.path. Should we accept pip outside of purelib (I don't see why not).

**Comment by MrBitBucket** [comment] 2021-08-06 14:55
OK I get a wheel with this sequence (here starting virtualenv is 16.7.10)

> cd ~/tmp
> hg clone https://hg.reportlab.com/hg/rlextra
> python39 -mvirtualenv rlextra/.py39
> cd  rlextra/
> . .py39/bin/activate
> pip install build[virtualenv]
> python -mbuild --wheel
> ls -l dist
> total 1904
> -rw-r--r-- 1 user user 1945789 Aug  6 15:37 rlextra-3.6.1-py3-none-any.whl

This sequence also works and pip comes from the venv
> cd ~/tmp
> hg clone https://hg.reportlab.com/hg/rlextra
> python39 -mvenv rlextra/.py39
> cd  rlextra/
> . .py39/bin/activate
> pip install build
> python -mbuild --wheel
> ls -l dist
> total 1904
> -rw-r--r-- 1 robin robin 1945767 Aug  6 15:47 rlextra-3.6.1-py3-none-any.whl

**Comment by FFY00** [comment] 2021-08-07 00:31
> Should we accept pip outside of purelib (I don't see why not).

I think we should.

**Comment by layday** [comment] 2021-08-07 09:36
IIRC the reason we started installing pip in the build env is because pip hardcodes the path to the Python executable in scripts, so we'd be looking for a way to call pip with the venv's Python without putting a whole host of other packages on the Python path.

**Comment by layday** [comment] 2021-08-07 09:40
https://github.com/pypa/build/issues/214#issuecomment-772110314

**Comment by layday** [comment] 2021-08-07 10:05
What we could do is something similar to what pipx does - install pip at a predetermined location and put it on the build envs' Python path.  This would speed up venv creation by a considerable margin and we would also avoid having to uninstall setuptools.  On the flip side, it might complicate debugging.

**Comment by gaborbernat** [comment] 2021-08-07 10:30
@layday note this only applies when using the venv, in case of virtualenv the pip caching is done already by virtualenv.

**Comment by layday** [comment] 2021-12-29 14:47
Closing as duplicate of https://github.com/pypa/build/issues/266.

**Closed by layday** 2021-12-29 14:47 UTC
Labels: bug
