### ISSUE TITLE
Build creates a tar.gz sdist with a deeply nested file structure

### ISSUE THREAD

**Issue by BrendanPC** [pypa/build#255] opened 2021-03-09 22:05 UTC
My project exists in a directory like so:
**/c/users/b/projects/repo/foo/foo-py**
With my setup.py and pyproject.toml residing in **/c/users/b/projects/repo/foo**, and the source code under that in foo-py/.

When I run build with no options, it creates **/c/users/b/projects/repo/foo/dist** as I'd expect, with a wheel file and a tar.gz file.

The wheel file is normal, but the tar.gz archive for some reason has nested the entire source path into itself, meaning that if I extract the archive in place it looks like this:
**/c/users/b/projects/repo/foo/dist/foo.tar.gz**
--> extract in place
**/c/users/b/projects/repo/foo/dist/C_/users/b/projects/repo/foo/dist/tmp9_n1v5sw/foo.tar**

This definitely seems wrong, there's no reason for the entire path that the source happened to reside in when it was packaged be included in the archive.

If I simply run `python setup.py sdist` myself, the archive created is normal and doesn't have this double nested structure. I'm new to using this build tool so may just be overlooking some configuration, but I can't find any trace of anyone having a similar problem.

Please advise, thank you!

**Comment by FFY00** [comment] 2021-03-09 22:13
Well, this shouldn't be a problem of the build tool, as it does not generate the sdist, we merely ask the backend to do so. It should be a problem of setuptools, but it's weird that the behavior is different. setuptools does, naturally, get invoked via a different code path, so the problem may lay there somewhere.

**Comment by henryiii** [comment] 2021-03-10 04:23
Though if you can build the SDist from a fixed version of Python (say in CI), then it should work everywhere after that.

**Comment by jaraco** [comment] 2021-03-12 15:16
Thanks layday for capturing all that state.

> Nothing to be done but upgrade Python I'm afraid.

Actually, Setuptools is in the process of adopting distutils and does include a copy of distutils. So fixes that were applied to distutils in Python should be ported to pypa/distutils and subsequently released with Setuptools, made available for users with `SETUPTOOLS_USE_DISTUTILS=local` (and eventually all), irrespective of Python version.

**Comment by jaraco** [comment] 2021-03-12 15:16
Closing in favor of pypa/setuptools#2178.

**Closed by jaraco** 2021-03-12 15:16 UTC

**Comment by jaraco** [comment] 2021-03-12 15:38
> So fixes that were applied to distutils in Python should be ported to pypa/distutils...

I was mistaken. The changes did not involve distutils. The only option for supporting older Pythons will be to create a backport of tarfile (similar to what you see in `backports.functools_lru_cache` or `configparser` or `singledispatch`). If the issue is pressing enough that someone wishes to create such a backport, I'd be happy to help guide the creation of such a project.
